debug = true

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[acme]
email = "user@domain.com"
storage = "acme.json"
acmeLogging = true
entryPoint = "https"

[acme.dnsChallenge]
  provider = "godaddy"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "*.domain.com"
[[acme.domains]]
  main = "domain.com"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
swarmMode = true